#!/bin/bash
function download_files() {
    local files=("$@")
    for file in "${files[@]}"
    do
        wget -Nq "$file"
    done
}

function create_directory() {
    local dir_url=$1
    local dir_name=$(basename "$dir_url")
    dir_name_filtered=$(echo $dir_name | awk '{print $1}' FS='?')
    mkdir "$dir_name_filtered" 2>/dev/null
    cd "$dir_name_filtered"
    get_contents "$dir_url"
    cd ..
}

function get_contents() {
    local url=$1
    local github_token=$(grep -A 2 'github.com' ~/.netrc | grep 'password' | awk '{ print $NF }')
    local response=$(wget -qO- --header="Accept: application/vnd.github.v3+json"  --header="Authorization: token $github_token" "$url")
    echo "$response"
    local files=()
    local dirs=()
    for item in $(echo "$response" | jq -c '.[]')
    do
        local type=$(echo "$item" | jq -r '.type')
        local name=$(echo "$item" | jq -r '.name')
        if [[ "$type" == "file" ]]; then
            local download_url=$(echo "$item" | jq -r '.download_url')
            files+=("$download_url")
        elif [[ "$type" == "dir" ]]; then
            local dir_url=$(echo "$item" | jq -r '.url')
            dirs+=("$dir_url")
        fi
    done
    download_files "${files[@]}"
    for dir in "${dirs[@]}"
    do
        create_directory "$dir"
    done
}

function main(){
  frontend_dir="https://api.github.com/repos/alberttsg/frontend-nomadList/contents"
  backend_dir="https://api.github.com/repos/alberttsg/frontend-nomadList/contents"
  api_dir="https://api.github.com/repos/alberttsg/frontend-nomadList/contents"
  cd './frontend'
  get_contents "$frontend_dir"
  cd ../backend
  echo 'TODO:'
  cd ../api
  echo 'TODO:'
  cd ..

}

main